# Generated by Django 3.2.9 on 2021-11-08 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('preview', models.CharField(max_length=200, verbose_name='Краткая информация')),
                ('country', models.CharField(max_length=50, verbose_name='Страна')),
                ('town', models.CharField(max_length=50, verbose_name='Город')),
                ('organization', models.CharField(max_length=50, verbose_name='Организация')),
                ('telephone', models.PositiveBigIntegerField(verbose_name='Телефон')),
                ('email', models.EmailField(max_length=50, verbose_name='Электронная почта')),
                ('date_of_creation', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_of_change', models.DateField(auto_now=True, verbose_name='Дата изменения')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
    ]
